server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qi?useUnicode=true&characterEncoding=utf-8
    data-password: root
    data-username: root
  redis:
    port: 6379
    host: localhost
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /root
  data:
    mongodb:
      host: localhost
      port: 27017
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .ftl
    enabled: true
    content-type: text/html
    template-loader-path: classpath:/templates/
  mybatis:
    mapper-locations: classpath:com/mr/mapper/*.xml
    type-aliases-package: com.mr.entity

